[16.0][ADD] edi_sale_edifact_oca
QuocDuong1306/edi-framework pull request #6
Opened 2023-10-10 09:38 UTC by QuocDuong1306

- Not done, need to rewrite the tests
- The test of `edi_sale_ubl_oca` in v14 was failed too

2023-10-17 08:21 UTC, QuocDuong1306 commented
Updated test cases !

2023-10-19 04:24 UTC, nilshamerlinck requested changes
(will review again when all state related is removed)

2023-10-19 04:24 UTC, nilshamerlinck commented on edi_sale_edifact_oca/demo/edi_exchange_type.xml
> +      <field name="backend_type_id" ref="edi_edifact_oca.edi_backend_type_edifact" />
```suggestion
      <field name="backend_id" ref="edi_edifact_oca.edi_backend_edifact_demo" />
      <field name="backend_type_id" ref="edi_edifact_oca.edi_backend_type_edifact" />
```

2023-10-19 08:48 UTC, QuocDuong1306 commented
Hi @nilshamerlinck , could you have a look?

2023-10-19 09:21 UTC, nilshamerlinck approved these changes

2023-12-14 09:28 UTC, merged