[16.0][ADD] edi_account_edifact_oca
QuocDuong1306/edi-framework pull request #7
Opened 2023-10-30 10:03 UTC by QuocDuong1306

Draft state

2023-10-30 10:13 UTC, nilshamerlinck requested changes

2023-10-30 10:13 UTC, nilshamerlinck commented on edi_account_edifact_oca/components/listener.py
> +class MyEventListener(Component):
nitpick: can probably find a better name

2023-10-30 10:13 UTC, nilshamerlinck commented on edi_account_edifact_oca/components/validate.py
> +    def validate(self, value):
validation makes sense for xml files to validate using a xsd, but for edifact I don't think we need it

2023-10-30 10:13 UTC, nilshamerlinck commented on edi_account_edifact_oca/demo/edi_exchange_type.xml
> +    default_confirm_order: false
?

2023-10-30 10:13 UTC, nilshamerlinck commented on edi_account_edifact_oca/demo/edi_exchange_type.xml
> +    default_confirm_order: false
unrelated

2023-10-30 10:13 UTC, nilshamerlinck commented
where do you check that the invoice's customer is linked with an edi backend?

2023-10-30 10:16 UTC, QuocDuong1306 commented on edi_account_edifact_oca/demo/edi_exchange_type.xml
> +    default_confirm_order: false
Ah, i forgot removing when copy/paste

2023-11-01 08:25 UTC, QuocDuong1306 commented
I updated

2023-11-08 03:57 UTC, nilshamerlinck approved these changes

2023-11-08 03:57 UTC, nilshamerlinck commented on edi_account_edifact_oca/components/listener.py
> +        """Add your code here about creation of record"""
old docstring?

2024-05-09 02:56 UTC, closed without merging